[package]
name = "web"
version = "0.1.0"
license = "ISC"
edition = "2018"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
jsx-one = {git="https://github.com/jsx-one/jsx-one.git"}

[dependencies.neon]
version = "0.9"
default-features = false
features = ["napi-6"]
